services:
  - type: web
    name: portaudio installation
    env: python
    buildCommand: |
      if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install portaudio
      else
        apt-get update && apt-get install -y portaudio19-dev
      fi
      pip install -r requirements.txt
    startCommand: your-start-command
